name: Karate API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 14 * * 1' # Lunes 09:00 AM PET (14:00 UTC)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run Karate Tests
      run: mvn test

    - name: Upload Karate Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: karate-reports
        path: target/karate-reports/